from pydantic import BaseModel

class ContractsModels(BaseModel):
    firstname: str
    rs_segundonombre: str
    middlename: str
    lastname: str
    rs_fechanacimiento: str
    mobilephone: str
    rs_rfc: str
    rs_curp: str
    emailaddress1: str
    rs_genero: str
    rs_paisnacimiento: str
    rs_lugarnacimiento: str
    rs_nacionalidad: str
    address1_line1: str
    address1_line2: str
    address1_line3: str
    address1_postalcode: str
    rs_entidadfederativa: str
    rs_municipio: str
    rs_colonia: str
    interviewid: str
    telephone1: str
    rs_coloniaid: str
    rs_numerocuenta: str
    rs_numerocliente: str
    rs_cuentaclabemambu: str
    rs_clave: str
    rs_fechaapertura: str